from enum import Enum

class Constants(Enum):
    WEIGHT_LIMIT = 800
    AMT_TRUCKS = 10
    POPULATION_SIZE = 100
    GENERATIONS = 500
    AMT_TOURNAMENT_PARTICIPANTS = 8 # should be even number
    MUTATION_RATE = 0.1
    CROSSOVER_RATE = 0.8
    AVG_FITNESS_DELTA_THRESHOLD = 0.1
    LATE_FEE_WEIGHT = 0.7