from enum import Enum

class Constants(Enum):
    WEIGHT_LIMIT = 800.0
    AMT_TRUCKS = 10
    POPULATION_SIZE = 50
    AMT_PACKAGES = 100
    AMT_TOURNAMENT_PARTICIPANTS = 1
    MUTATION_RATE = 0.08
    CROSSOVER_RATE = 0.8
    AVG_FITNESS_DELTA_THRESHOLD = 0.5